name: 'Frontend Continuous Integration'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  lint-job:
    name: Linting
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run lint check
        run: npm run lint

  test-job:
    name: Testing job
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

  build:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

      